[Service]
SetCredentialEncrypted=pocketbase-encryption-key: \
        Whxqht+dQJax1aZeCGLxmiAAAAABAAAADAAAABAAAACEDVnckUMj7qwo1V8AAAAA0VoVFzT/eWFsY9Y \
        83fE2/79ysOUc6TlhXmjIFi7Z5GG03uT2QqA9lqOTq1/ep/S9LF6sV+ofs2XNI5aRfskZZgTmUDIj8f \
        0hq4UBVLhE02vt6ApEfyqflocfEPHuGwqMWA==
