[Service]
SetCredentialEncrypted=pocketbase-encryption-key: \
        Whxqht+dQJax1aZeCGLxmiAAAAABAAAADAAAABAAAABsEzHwADySboTlz+MAAAAA6Wg2cLVloQWGAoo \
        vM5eWtoBQ2LDxkWImvhFU8XvpkYzA6c2bGBX2kRfOLWN5Hz41T0gRH6vrt5+0S4njuE9wIKEujTQCMM \
        jjybt4Dhm9TOBbDfCjF1ncO9aDRYgr/e3gRbHkDbXZA6O1eLDxbdao3m3dKJu4xIrw1VQ0eekUwZkn
